spring:
  application:
    name: member
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  typeAliasesPackage: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  typeEnumsPackage: com.example.demo.enums
  global-config:
    db-config:
      table-underline: true
      field-strategy: not-null
      capital-mode: true
      column-like: true
      id-type: auto