spring:
  application:
    name: member
  datasource:
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root

mybatis-plus:
  typeAliasesPackage: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml
  typeEnumsPackage: com.example.demo.enums

logging:
  level:
    root: warn
    com.example.demo.dao: trace
  pattern:
    console: '%p%m%n'
